version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/atlas_code"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/atlas_code/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/atlas_code_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/atlas_code_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/atlas_code_ios"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/atlas_code_linux"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/atlas_code_macos"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/atlas_code_web"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/atlas_code_windows"
    schedule:
      interval: "daily"